### ISSUE TITLE
Use cases for PRIDE experiment database

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Archive/pride-mongodb-repo#1]
Here all use cases for PRIDE Experiments. 

- [ ] Insert/Update/Delete  a PRIDE Project.  
- [ ] Insert/Update/Delete a Project Files

**Comment by javizca** [comment]
In order of relevance (on top what it was mentioned above by Yasset):

1. Add references to a dataset (also delete in case of errors)
2. Add project tags (also delete in case of errors)
3. Update descriptions (sample description, data analysis description)
4. Add grant number (also delete in case of errors)
5. Add an additional PI (also delete in case of errors)
6. 5. Add URLs for the corresponding datasets in other databases (e.g. transcriptomics data in GEO/ArrayExpress) (also delete in case of errors)
